// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sl_global.proto

#ifndef PROTOBUF_sl_5fglobal_2eproto__INCLUDED
#define PROTOBUF_sl_5fglobal_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "sl_common_types.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_sl_5fglobal_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSLInitMsgImpl();
void InitDefaultsSLInitMsg();
void InitDefaultsSLInitMsgRspImpl();
void InitDefaultsSLInitMsgRsp();
void InitDefaultsSLGlobalNotifImpl();
void InitDefaultsSLGlobalNotif();
void InitDefaultsSLGlobalsGetMsgImpl();
void InitDefaultsSLGlobalsGetMsg();
void InitDefaultsSLGlobalsGetMsgRspImpl();
void InitDefaultsSLGlobalsGetMsgRsp();
inline void InitDefaults() {
  InitDefaultsSLInitMsg();
  InitDefaultsSLInitMsgRsp();
  InitDefaultsSLGlobalNotif();
  InitDefaultsSLGlobalsGetMsg();
  InitDefaultsSLGlobalsGetMsgRsp();
}
}  // namespace protobuf_sl_5fglobal_2eproto
namespace service_layer {
class SLGlobalNotif;
class SLGlobalNotifDefaultTypeInternal;
extern SLGlobalNotifDefaultTypeInternal _SLGlobalNotif_default_instance_;
class SLGlobalsGetMsg;
class SLGlobalsGetMsgDefaultTypeInternal;
extern SLGlobalsGetMsgDefaultTypeInternal _SLGlobalsGetMsg_default_instance_;
class SLGlobalsGetMsgRsp;
class SLGlobalsGetMsgRspDefaultTypeInternal;
extern SLGlobalsGetMsgRspDefaultTypeInternal _SLGlobalsGetMsgRsp_default_instance_;
class SLInitMsg;
class SLInitMsgDefaultTypeInternal;
extern SLInitMsgDefaultTypeInternal _SLInitMsg_default_instance_;
class SLInitMsgRsp;
class SLInitMsgRspDefaultTypeInternal;
extern SLInitMsgRspDefaultTypeInternal _SLInitMsgRsp_default_instance_;
}  // namespace service_layer
namespace service_layer {

enum SLGlobalNotifType {
  SL_GLOBAL_EVENT_TYPE_RESERVED = 0,
  SL_GLOBAL_EVENT_TYPE_ERROR = 1,
  SL_GLOBAL_EVENT_TYPE_HEARTBEAT = 2,
  SL_GLOBAL_EVENT_TYPE_VERSION = 3,
  SLGlobalNotifType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  SLGlobalNotifType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool SLGlobalNotifType_IsValid(int value);
const SLGlobalNotifType SLGlobalNotifType_MIN = SL_GLOBAL_EVENT_TYPE_RESERVED;
const SLGlobalNotifType SLGlobalNotifType_MAX = SL_GLOBAL_EVENT_TYPE_VERSION;
const int SLGlobalNotifType_ARRAYSIZE = SLGlobalNotifType_MAX + 1;

const ::google::protobuf::EnumDescriptor* SLGlobalNotifType_descriptor();
inline const ::std::string& SLGlobalNotifType_Name(SLGlobalNotifType value) {
  return ::google::protobuf::internal::NameOfEnum(
    SLGlobalNotifType_descriptor(), value);
}
inline bool SLGlobalNotifType_Parse(
    const ::std::string& name, SLGlobalNotifType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SLGlobalNotifType>(
    SLGlobalNotifType_descriptor(), name, value);
}
// ===================================================================

class SLInitMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:service_layer.SLInitMsg) */ {
 public:
  SLInitMsg();
  virtual ~SLInitMsg();

  SLInitMsg(const SLInitMsg& from);

  inline SLInitMsg& operator=(const SLInitMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SLInitMsg(SLInitMsg&& from) noexcept
    : SLInitMsg() {
    *this = ::std::move(from);
  }

  inline SLInitMsg& operator=(SLInitMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SLInitMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SLInitMsg* internal_default_instance() {
    return reinterpret_cast<const SLInitMsg*>(
               &_SLInitMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SLInitMsg* other);
  friend void swap(SLInitMsg& a, SLInitMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SLInitMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  SLInitMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SLInitMsg& from);
  void MergeFrom(const SLInitMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SLInitMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 MajorVer = 1;
  void clear_majorver();
  static const int kMajorVerFieldNumber = 1;
  ::google::protobuf::uint32 majorver() const;
  void set_majorver(::google::protobuf::uint32 value);

  // uint32 MinorVer = 2;
  void clear_minorver();
  static const int kMinorVerFieldNumber = 2;
  ::google::protobuf::uint32 minorver() const;
  void set_minorver(::google::protobuf::uint32 value);

  // uint32 SubVer = 3;
  void clear_subver();
  static const int kSubVerFieldNumber = 3;
  ::google::protobuf::uint32 subver() const;
  void set_subver(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:service_layer.SLInitMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 majorver_;
  ::google::protobuf::uint32 minorver_;
  ::google::protobuf::uint32 subver_;
  mutable int _cached_size_;
  friend struct ::protobuf_sl_5fglobal_2eproto::TableStruct;
  friend void ::protobuf_sl_5fglobal_2eproto::InitDefaultsSLInitMsgImpl();
};
// -------------------------------------------------------------------

class SLInitMsgRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:service_layer.SLInitMsgRsp) */ {
 public:
  SLInitMsgRsp();
  virtual ~SLInitMsgRsp();

  SLInitMsgRsp(const SLInitMsgRsp& from);

  inline SLInitMsgRsp& operator=(const SLInitMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SLInitMsgRsp(SLInitMsgRsp&& from) noexcept
    : SLInitMsgRsp() {
    *this = ::std::move(from);
  }

  inline SLInitMsgRsp& operator=(SLInitMsgRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SLInitMsgRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SLInitMsgRsp* internal_default_instance() {
    return reinterpret_cast<const SLInitMsgRsp*>(
               &_SLInitMsgRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SLInitMsgRsp* other);
  friend void swap(SLInitMsgRsp& a, SLInitMsgRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SLInitMsgRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  SLInitMsgRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SLInitMsgRsp& from);
  void MergeFrom(const SLInitMsgRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SLInitMsgRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 MajorVer = 1;
  void clear_majorver();
  static const int kMajorVerFieldNumber = 1;
  ::google::protobuf::uint32 majorver() const;
  void set_majorver(::google::protobuf::uint32 value);

  // uint32 MinorVer = 2;
  void clear_minorver();
  static const int kMinorVerFieldNumber = 2;
  ::google::protobuf::uint32 minorver() const;
  void set_minorver(::google::protobuf::uint32 value);

  // uint32 SubVer = 3;
  void clear_subver();
  static const int kSubVerFieldNumber = 3;
  ::google::protobuf::uint32 subver() const;
  void set_subver(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:service_layer.SLInitMsgRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 majorver_;
  ::google::protobuf::uint32 minorver_;
  ::google::protobuf::uint32 subver_;
  mutable int _cached_size_;
  friend struct ::protobuf_sl_5fglobal_2eproto::TableStruct;
  friend void ::protobuf_sl_5fglobal_2eproto::InitDefaultsSLInitMsgRspImpl();
};
// -------------------------------------------------------------------

class SLGlobalNotif : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:service_layer.SLGlobalNotif) */ {
 public:
  SLGlobalNotif();
  virtual ~SLGlobalNotif();

  SLGlobalNotif(const SLGlobalNotif& from);

  inline SLGlobalNotif& operator=(const SLGlobalNotif& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SLGlobalNotif(SLGlobalNotif&& from) noexcept
    : SLGlobalNotif() {
    *this = ::std::move(from);
  }

  inline SLGlobalNotif& operator=(SLGlobalNotif&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SLGlobalNotif& default_instance();

  enum EventCase {
    kInitRspMsg = 3,
    EVENT_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SLGlobalNotif* internal_default_instance() {
    return reinterpret_cast<const SLGlobalNotif*>(
               &_SLGlobalNotif_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(SLGlobalNotif* other);
  friend void swap(SLGlobalNotif& a, SLGlobalNotif& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SLGlobalNotif* New() const PROTOBUF_FINAL { return New(NULL); }

  SLGlobalNotif* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SLGlobalNotif& from);
  void MergeFrom(const SLGlobalNotif& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SLGlobalNotif* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .service_layer.SLErrorStatus ErrStatus = 2;
  bool has_errstatus() const;
  void clear_errstatus();
  static const int kErrStatusFieldNumber = 2;
  const ::service_layer::SLErrorStatus& errstatus() const;
  ::service_layer::SLErrorStatus* release_errstatus();
  ::service_layer::SLErrorStatus* mutable_errstatus();
  void set_allocated_errstatus(::service_layer::SLErrorStatus* errstatus);

  // .service_layer.SLGlobalNotifType EventType = 1;
  void clear_eventtype();
  static const int kEventTypeFieldNumber = 1;
  ::service_layer::SLGlobalNotifType eventtype() const;
  void set_eventtype(::service_layer::SLGlobalNotifType value);

  // .service_layer.SLInitMsgRsp InitRspMsg = 3;
  bool has_initrspmsg() const;
  void clear_initrspmsg();
  static const int kInitRspMsgFieldNumber = 3;
  const ::service_layer::SLInitMsgRsp& initrspmsg() const;
  ::service_layer::SLInitMsgRsp* release_initrspmsg();
  ::service_layer::SLInitMsgRsp* mutable_initrspmsg();
  void set_allocated_initrspmsg(::service_layer::SLInitMsgRsp* initrspmsg);

  EventCase Event_case() const;
  // @@protoc_insertion_point(class_scope:service_layer.SLGlobalNotif)
 private:
  void set_has_initrspmsg();

  inline bool has_Event() const;
  void clear_Event();
  inline void clear_has_Event();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::service_layer::SLErrorStatus* errstatus_;
  int eventtype_;
  union EventUnion {
    EventUnion() {}
    ::service_layer::SLInitMsgRsp* initrspmsg_;
  } Event_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_sl_5fglobal_2eproto::TableStruct;
  friend void ::protobuf_sl_5fglobal_2eproto::InitDefaultsSLGlobalNotifImpl();
};
// -------------------------------------------------------------------

class SLGlobalsGetMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:service_layer.SLGlobalsGetMsg) */ {
 public:
  SLGlobalsGetMsg();
  virtual ~SLGlobalsGetMsg();

  SLGlobalsGetMsg(const SLGlobalsGetMsg& from);

  inline SLGlobalsGetMsg& operator=(const SLGlobalsGetMsg& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SLGlobalsGetMsg(SLGlobalsGetMsg&& from) noexcept
    : SLGlobalsGetMsg() {
    *this = ::std::move(from);
  }

  inline SLGlobalsGetMsg& operator=(SLGlobalsGetMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SLGlobalsGetMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SLGlobalsGetMsg* internal_default_instance() {
    return reinterpret_cast<const SLGlobalsGetMsg*>(
               &_SLGlobalsGetMsg_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(SLGlobalsGetMsg* other);
  friend void swap(SLGlobalsGetMsg& a, SLGlobalsGetMsg& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SLGlobalsGetMsg* New() const PROTOBUF_FINAL { return New(NULL); }

  SLGlobalsGetMsg* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SLGlobalsGetMsg& from);
  void MergeFrom(const SLGlobalsGetMsg& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SLGlobalsGetMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:service_layer.SLGlobalsGetMsg)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct ::protobuf_sl_5fglobal_2eproto::TableStruct;
  friend void ::protobuf_sl_5fglobal_2eproto::InitDefaultsSLGlobalsGetMsgImpl();
};
// -------------------------------------------------------------------

class SLGlobalsGetMsgRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:service_layer.SLGlobalsGetMsgRsp) */ {
 public:
  SLGlobalsGetMsgRsp();
  virtual ~SLGlobalsGetMsgRsp();

  SLGlobalsGetMsgRsp(const SLGlobalsGetMsgRsp& from);

  inline SLGlobalsGetMsgRsp& operator=(const SLGlobalsGetMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SLGlobalsGetMsgRsp(SLGlobalsGetMsgRsp&& from) noexcept
    : SLGlobalsGetMsgRsp() {
    *this = ::std::move(from);
  }

  inline SLGlobalsGetMsgRsp& operator=(SLGlobalsGetMsgRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SLGlobalsGetMsgRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SLGlobalsGetMsgRsp* internal_default_instance() {
    return reinterpret_cast<const SLGlobalsGetMsgRsp*>(
               &_SLGlobalsGetMsgRsp_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(SLGlobalsGetMsgRsp* other);
  friend void swap(SLGlobalsGetMsgRsp& a, SLGlobalsGetMsgRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SLGlobalsGetMsgRsp* New() const PROTOBUF_FINAL { return New(NULL); }

  SLGlobalsGetMsgRsp* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SLGlobalsGetMsgRsp& from);
  void MergeFrom(const SLGlobalsGetMsgRsp& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SLGlobalsGetMsgRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .service_layer.SLErrorStatus ErrStatus = 1;
  bool has_errstatus() const;
  void clear_errstatus();
  static const int kErrStatusFieldNumber = 1;
  const ::service_layer::SLErrorStatus& errstatus() const;
  ::service_layer::SLErrorStatus* release_errstatus();
  ::service_layer::SLErrorStatus* mutable_errstatus();
  void set_allocated_errstatus(::service_layer::SLErrorStatus* errstatus);

  // uint32 MaxVrfNameLength = 2;
  void clear_maxvrfnamelength();
  static const int kMaxVrfNameLengthFieldNumber = 2;
  ::google::protobuf::uint32 maxvrfnamelength() const;
  void set_maxvrfnamelength(::google::protobuf::uint32 value);

  // uint32 MaxInterfaceNameLength = 3;
  void clear_maxinterfacenamelength();
  static const int kMaxInterfaceNameLengthFieldNumber = 3;
  ::google::protobuf::uint32 maxinterfacenamelength() const;
  void set_maxinterfacenamelength(::google::protobuf::uint32 value);

  // uint32 MaxPathsPerEntry = 4;
  void clear_maxpathsperentry();
  static const int kMaxPathsPerEntryFieldNumber = 4;
  ::google::protobuf::uint32 maxpathsperentry() const;
  void set_maxpathsperentry(::google::protobuf::uint32 value);

  // uint32 MaxPrimaryPathPerEntry = 5;
  void clear_maxprimarypathperentry();
  static const int kMaxPrimaryPathPerEntryFieldNumber = 5;
  ::google::protobuf::uint32 maxprimarypathperentry() const;
  void set_maxprimarypathperentry(::google::protobuf::uint32 value);

  // uint32 MaxBackupPathPerEntry = 6;
  void clear_maxbackuppathperentry();
  static const int kMaxBackupPathPerEntryFieldNumber = 6;
  ::google::protobuf::uint32 maxbackuppathperentry() const;
  void set_maxbackuppathperentry(::google::protobuf::uint32 value);

  // uint32 MaxMplsLabelsPerPath = 7;
  void clear_maxmplslabelsperpath();
  static const int kMaxMplsLabelsPerPathFieldNumber = 7;
  ::google::protobuf::uint32 maxmplslabelsperpath() const;
  void set_maxmplslabelsperpath(::google::protobuf::uint32 value);

  // uint32 MinPrimaryPathIdNum = 8;
  void clear_minprimarypathidnum();
  static const int kMinPrimaryPathIdNumFieldNumber = 8;
  ::google::protobuf::uint32 minprimarypathidnum() const;
  void set_minprimarypathidnum(::google::protobuf::uint32 value);

  // uint32 MaxPrimaryPathIdNum = 9;
  void clear_maxprimarypathidnum();
  static const int kMaxPrimaryPathIdNumFieldNumber = 9;
  ::google::protobuf::uint32 maxprimarypathidnum() const;
  void set_maxprimarypathidnum(::google::protobuf::uint32 value);

  // uint32 MinBackupPathIdNum = 10;
  void clear_minbackuppathidnum();
  static const int kMinBackupPathIdNumFieldNumber = 10;
  ::google::protobuf::uint32 minbackuppathidnum() const;
  void set_minbackuppathidnum(::google::protobuf::uint32 value);

  // uint32 MaxBackupPathIdNum = 11;
  void clear_maxbackuppathidnum();
  static const int kMaxBackupPathIdNumFieldNumber = 11;
  ::google::protobuf::uint32 maxbackuppathidnum() const;
  void set_maxbackuppathidnum(::google::protobuf::uint32 value);

  // uint32 MaxRemoteAddressNum = 12;
  void clear_maxremoteaddressnum();
  static const int kMaxRemoteAddressNumFieldNumber = 12;
  ::google::protobuf::uint32 maxremoteaddressnum() const;
  void set_maxremoteaddressnum(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:service_layer.SLGlobalsGetMsgRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::service_layer::SLErrorStatus* errstatus_;
  ::google::protobuf::uint32 maxvrfnamelength_;
  ::google::protobuf::uint32 maxinterfacenamelength_;
  ::google::protobuf::uint32 maxpathsperentry_;
  ::google::protobuf::uint32 maxprimarypathperentry_;
  ::google::protobuf::uint32 maxbackuppathperentry_;
  ::google::protobuf::uint32 maxmplslabelsperpath_;
  ::google::protobuf::uint32 minprimarypathidnum_;
  ::google::protobuf::uint32 maxprimarypathidnum_;
  ::google::protobuf::uint32 minbackuppathidnum_;
  ::google::protobuf::uint32 maxbackuppathidnum_;
  ::google::protobuf::uint32 maxremoteaddressnum_;
  mutable int _cached_size_;
  friend struct ::protobuf_sl_5fglobal_2eproto::TableStruct;
  friend void ::protobuf_sl_5fglobal_2eproto::InitDefaultsSLGlobalsGetMsgRspImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SLInitMsg

// uint32 MajorVer = 1;
inline void SLInitMsg::clear_majorver() {
  majorver_ = 0u;
}
inline ::google::protobuf::uint32 SLInitMsg::majorver() const {
  // @@protoc_insertion_point(field_get:service_layer.SLInitMsg.MajorVer)
  return majorver_;
}
inline void SLInitMsg::set_majorver(::google::protobuf::uint32 value) {
  
  majorver_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLInitMsg.MajorVer)
}

// uint32 MinorVer = 2;
inline void SLInitMsg::clear_minorver() {
  minorver_ = 0u;
}
inline ::google::protobuf::uint32 SLInitMsg::minorver() const {
  // @@protoc_insertion_point(field_get:service_layer.SLInitMsg.MinorVer)
  return minorver_;
}
inline void SLInitMsg::set_minorver(::google::protobuf::uint32 value) {
  
  minorver_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLInitMsg.MinorVer)
}

// uint32 SubVer = 3;
inline void SLInitMsg::clear_subver() {
  subver_ = 0u;
}
inline ::google::protobuf::uint32 SLInitMsg::subver() const {
  // @@protoc_insertion_point(field_get:service_layer.SLInitMsg.SubVer)
  return subver_;
}
inline void SLInitMsg::set_subver(::google::protobuf::uint32 value) {
  
  subver_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLInitMsg.SubVer)
}

// -------------------------------------------------------------------

// SLInitMsgRsp

// uint32 MajorVer = 1;
inline void SLInitMsgRsp::clear_majorver() {
  majorver_ = 0u;
}
inline ::google::protobuf::uint32 SLInitMsgRsp::majorver() const {
  // @@protoc_insertion_point(field_get:service_layer.SLInitMsgRsp.MajorVer)
  return majorver_;
}
inline void SLInitMsgRsp::set_majorver(::google::protobuf::uint32 value) {
  
  majorver_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLInitMsgRsp.MajorVer)
}

// uint32 MinorVer = 2;
inline void SLInitMsgRsp::clear_minorver() {
  minorver_ = 0u;
}
inline ::google::protobuf::uint32 SLInitMsgRsp::minorver() const {
  // @@protoc_insertion_point(field_get:service_layer.SLInitMsgRsp.MinorVer)
  return minorver_;
}
inline void SLInitMsgRsp::set_minorver(::google::protobuf::uint32 value) {
  
  minorver_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLInitMsgRsp.MinorVer)
}

// uint32 SubVer = 3;
inline void SLInitMsgRsp::clear_subver() {
  subver_ = 0u;
}
inline ::google::protobuf::uint32 SLInitMsgRsp::subver() const {
  // @@protoc_insertion_point(field_get:service_layer.SLInitMsgRsp.SubVer)
  return subver_;
}
inline void SLInitMsgRsp::set_subver(::google::protobuf::uint32 value) {
  
  subver_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLInitMsgRsp.SubVer)
}

// -------------------------------------------------------------------

// SLGlobalNotif

// .service_layer.SLGlobalNotifType EventType = 1;
inline void SLGlobalNotif::clear_eventtype() {
  eventtype_ = 0;
}
inline ::service_layer::SLGlobalNotifType SLGlobalNotif::eventtype() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalNotif.EventType)
  return static_cast< ::service_layer::SLGlobalNotifType >(eventtype_);
}
inline void SLGlobalNotif::set_eventtype(::service_layer::SLGlobalNotifType value) {
  
  eventtype_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalNotif.EventType)
}

// .service_layer.SLErrorStatus ErrStatus = 2;
inline bool SLGlobalNotif::has_errstatus() const {
  return this != internal_default_instance() && errstatus_ != NULL;
}
inline const ::service_layer::SLErrorStatus& SLGlobalNotif::errstatus() const {
  const ::service_layer::SLErrorStatus* p = errstatus_;
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalNotif.ErrStatus)
  return p != NULL ? *p : *reinterpret_cast<const ::service_layer::SLErrorStatus*>(
      &::service_layer::_SLErrorStatus_default_instance_);
}
inline ::service_layer::SLErrorStatus* SLGlobalNotif::release_errstatus() {
  // @@protoc_insertion_point(field_release:service_layer.SLGlobalNotif.ErrStatus)
  
  ::service_layer::SLErrorStatus* temp = errstatus_;
  errstatus_ = NULL;
  return temp;
}
inline ::service_layer::SLErrorStatus* SLGlobalNotif::mutable_errstatus() {
  
  if (errstatus_ == NULL) {
    errstatus_ = new ::service_layer::SLErrorStatus;
  }
  // @@protoc_insertion_point(field_mutable:service_layer.SLGlobalNotif.ErrStatus)
  return errstatus_;
}
inline void SLGlobalNotif::set_allocated_errstatus(::service_layer::SLErrorStatus* errstatus) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(errstatus_);
  }
  if (errstatus) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      errstatus = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, errstatus, submessage_arena);
    }
    
  } else {
    
  }
  errstatus_ = errstatus;
  // @@protoc_insertion_point(field_set_allocated:service_layer.SLGlobalNotif.ErrStatus)
}

// .service_layer.SLInitMsgRsp InitRspMsg = 3;
inline bool SLGlobalNotif::has_initrspmsg() const {
  return Event_case() == kInitRspMsg;
}
inline void SLGlobalNotif::set_has_initrspmsg() {
  _oneof_case_[0] = kInitRspMsg;
}
inline void SLGlobalNotif::clear_initrspmsg() {
  if (has_initrspmsg()) {
    delete Event_.initrspmsg_;
    clear_has_Event();
  }
}
inline ::service_layer::SLInitMsgRsp* SLGlobalNotif::release_initrspmsg() {
  // @@protoc_insertion_point(field_release:service_layer.SLGlobalNotif.InitRspMsg)
  if (has_initrspmsg()) {
    clear_has_Event();
      ::service_layer::SLInitMsgRsp* temp = Event_.initrspmsg_;
    Event_.initrspmsg_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline const ::service_layer::SLInitMsgRsp& SLGlobalNotif::initrspmsg() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalNotif.InitRspMsg)
  return has_initrspmsg()
      ? *Event_.initrspmsg_
      : *reinterpret_cast< ::service_layer::SLInitMsgRsp*>(&::service_layer::_SLInitMsgRsp_default_instance_);
}
inline ::service_layer::SLInitMsgRsp* SLGlobalNotif::mutable_initrspmsg() {
  if (!has_initrspmsg()) {
    clear_Event();
    set_has_initrspmsg();
    Event_.initrspmsg_ = new ::service_layer::SLInitMsgRsp;
  }
  // @@protoc_insertion_point(field_mutable:service_layer.SLGlobalNotif.InitRspMsg)
  return Event_.initrspmsg_;
}

inline bool SLGlobalNotif::has_Event() const {
  return Event_case() != EVENT_NOT_SET;
}
inline void SLGlobalNotif::clear_has_Event() {
  _oneof_case_[0] = EVENT_NOT_SET;
}
inline SLGlobalNotif::EventCase SLGlobalNotif::Event_case() const {
  return SLGlobalNotif::EventCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// SLGlobalsGetMsg

// -------------------------------------------------------------------

// SLGlobalsGetMsgRsp

// .service_layer.SLErrorStatus ErrStatus = 1;
inline bool SLGlobalsGetMsgRsp::has_errstatus() const {
  return this != internal_default_instance() && errstatus_ != NULL;
}
inline const ::service_layer::SLErrorStatus& SLGlobalsGetMsgRsp::errstatus() const {
  const ::service_layer::SLErrorStatus* p = errstatus_;
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.ErrStatus)
  return p != NULL ? *p : *reinterpret_cast<const ::service_layer::SLErrorStatus*>(
      &::service_layer::_SLErrorStatus_default_instance_);
}
inline ::service_layer::SLErrorStatus* SLGlobalsGetMsgRsp::release_errstatus() {
  // @@protoc_insertion_point(field_release:service_layer.SLGlobalsGetMsgRsp.ErrStatus)
  
  ::service_layer::SLErrorStatus* temp = errstatus_;
  errstatus_ = NULL;
  return temp;
}
inline ::service_layer::SLErrorStatus* SLGlobalsGetMsgRsp::mutable_errstatus() {
  
  if (errstatus_ == NULL) {
    errstatus_ = new ::service_layer::SLErrorStatus;
  }
  // @@protoc_insertion_point(field_mutable:service_layer.SLGlobalsGetMsgRsp.ErrStatus)
  return errstatus_;
}
inline void SLGlobalsGetMsgRsp::set_allocated_errstatus(::service_layer::SLErrorStatus* errstatus) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(errstatus_);
  }
  if (errstatus) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      errstatus = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, errstatus, submessage_arena);
    }
    
  } else {
    
  }
  errstatus_ = errstatus;
  // @@protoc_insertion_point(field_set_allocated:service_layer.SLGlobalsGetMsgRsp.ErrStatus)
}

// uint32 MaxVrfNameLength = 2;
inline void SLGlobalsGetMsgRsp::clear_maxvrfnamelength() {
  maxvrfnamelength_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::maxvrfnamelength() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MaxVrfNameLength)
  return maxvrfnamelength_;
}
inline void SLGlobalsGetMsgRsp::set_maxvrfnamelength(::google::protobuf::uint32 value) {
  
  maxvrfnamelength_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MaxVrfNameLength)
}

// uint32 MaxInterfaceNameLength = 3;
inline void SLGlobalsGetMsgRsp::clear_maxinterfacenamelength() {
  maxinterfacenamelength_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::maxinterfacenamelength() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MaxInterfaceNameLength)
  return maxinterfacenamelength_;
}
inline void SLGlobalsGetMsgRsp::set_maxinterfacenamelength(::google::protobuf::uint32 value) {
  
  maxinterfacenamelength_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MaxInterfaceNameLength)
}

// uint32 MaxPathsPerEntry = 4;
inline void SLGlobalsGetMsgRsp::clear_maxpathsperentry() {
  maxpathsperentry_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::maxpathsperentry() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MaxPathsPerEntry)
  return maxpathsperentry_;
}
inline void SLGlobalsGetMsgRsp::set_maxpathsperentry(::google::protobuf::uint32 value) {
  
  maxpathsperentry_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MaxPathsPerEntry)
}

// uint32 MaxPrimaryPathPerEntry = 5;
inline void SLGlobalsGetMsgRsp::clear_maxprimarypathperentry() {
  maxprimarypathperentry_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::maxprimarypathperentry() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MaxPrimaryPathPerEntry)
  return maxprimarypathperentry_;
}
inline void SLGlobalsGetMsgRsp::set_maxprimarypathperentry(::google::protobuf::uint32 value) {
  
  maxprimarypathperentry_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MaxPrimaryPathPerEntry)
}

// uint32 MaxBackupPathPerEntry = 6;
inline void SLGlobalsGetMsgRsp::clear_maxbackuppathperentry() {
  maxbackuppathperentry_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::maxbackuppathperentry() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MaxBackupPathPerEntry)
  return maxbackuppathperentry_;
}
inline void SLGlobalsGetMsgRsp::set_maxbackuppathperentry(::google::protobuf::uint32 value) {
  
  maxbackuppathperentry_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MaxBackupPathPerEntry)
}

// uint32 MaxMplsLabelsPerPath = 7;
inline void SLGlobalsGetMsgRsp::clear_maxmplslabelsperpath() {
  maxmplslabelsperpath_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::maxmplslabelsperpath() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MaxMplsLabelsPerPath)
  return maxmplslabelsperpath_;
}
inline void SLGlobalsGetMsgRsp::set_maxmplslabelsperpath(::google::protobuf::uint32 value) {
  
  maxmplslabelsperpath_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MaxMplsLabelsPerPath)
}

// uint32 MinPrimaryPathIdNum = 8;
inline void SLGlobalsGetMsgRsp::clear_minprimarypathidnum() {
  minprimarypathidnum_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::minprimarypathidnum() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MinPrimaryPathIdNum)
  return minprimarypathidnum_;
}
inline void SLGlobalsGetMsgRsp::set_minprimarypathidnum(::google::protobuf::uint32 value) {
  
  minprimarypathidnum_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MinPrimaryPathIdNum)
}

// uint32 MaxPrimaryPathIdNum = 9;
inline void SLGlobalsGetMsgRsp::clear_maxprimarypathidnum() {
  maxprimarypathidnum_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::maxprimarypathidnum() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MaxPrimaryPathIdNum)
  return maxprimarypathidnum_;
}
inline void SLGlobalsGetMsgRsp::set_maxprimarypathidnum(::google::protobuf::uint32 value) {
  
  maxprimarypathidnum_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MaxPrimaryPathIdNum)
}

// uint32 MinBackupPathIdNum = 10;
inline void SLGlobalsGetMsgRsp::clear_minbackuppathidnum() {
  minbackuppathidnum_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::minbackuppathidnum() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MinBackupPathIdNum)
  return minbackuppathidnum_;
}
inline void SLGlobalsGetMsgRsp::set_minbackuppathidnum(::google::protobuf::uint32 value) {
  
  minbackuppathidnum_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MinBackupPathIdNum)
}

// uint32 MaxBackupPathIdNum = 11;
inline void SLGlobalsGetMsgRsp::clear_maxbackuppathidnum() {
  maxbackuppathidnum_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::maxbackuppathidnum() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MaxBackupPathIdNum)
  return maxbackuppathidnum_;
}
inline void SLGlobalsGetMsgRsp::set_maxbackuppathidnum(::google::protobuf::uint32 value) {
  
  maxbackuppathidnum_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MaxBackupPathIdNum)
}

// uint32 MaxRemoteAddressNum = 12;
inline void SLGlobalsGetMsgRsp::clear_maxremoteaddressnum() {
  maxremoteaddressnum_ = 0u;
}
inline ::google::protobuf::uint32 SLGlobalsGetMsgRsp::maxremoteaddressnum() const {
  // @@protoc_insertion_point(field_get:service_layer.SLGlobalsGetMsgRsp.MaxRemoteAddressNum)
  return maxremoteaddressnum_;
}
inline void SLGlobalsGetMsgRsp::set_maxremoteaddressnum(::google::protobuf::uint32 value) {
  
  maxremoteaddressnum_ = value;
  // @@protoc_insertion_point(field_set:service_layer.SLGlobalsGetMsgRsp.MaxRemoteAddressNum)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace service_layer

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::service_layer::SLGlobalNotifType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::service_layer::SLGlobalNotifType>() {
  return ::service_layer::SLGlobalNotifType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_sl_5fglobal_2eproto__INCLUDED
