// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: sl_route_ipv4.proto

#include "sl_route_ipv4.pb.h"
#include "sl_route_ipv4.grpc.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/channel_interface.h>
#include <grpc++/impl/codegen/client_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/rpc_service_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/sync_stream.h>
namespace service_layer {

static const char* SLRoutev4Oper_method_names[] = {
  "/service_layer.SLRoutev4Oper/SLRoutev4GlobalsGet",
  "/service_layer.SLRoutev4Oper/SLRoutev4GlobalStatsGet",
  "/service_layer.SLRoutev4Oper/SLRoutev4VrfRegOp",
  "/service_layer.SLRoutev4Oper/SLRoutev4VrfRegGet",
  "/service_layer.SLRoutev4Oper/SLRoutev4VrfGetStats",
  "/service_layer.SLRoutev4Oper/SLRoutev4Op",
  "/service_layer.SLRoutev4Oper/SLRoutev4Get",
  "/service_layer.SLRoutev4Oper/SLRoutev4OpStream",
  "/service_layer.SLRoutev4Oper/SLRoutev4GetStream",
};

std::unique_ptr< SLRoutev4Oper::Stub> SLRoutev4Oper::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  std::unique_ptr< SLRoutev4Oper::Stub> stub(new SLRoutev4Oper::Stub(channel));
  return stub;
}

SLRoutev4Oper::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SLRoutev4GlobalsGet_(SLRoutev4Oper_method_names[0], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SLRoutev4GlobalStatsGet_(SLRoutev4Oper_method_names[1], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SLRoutev4VrfRegOp_(SLRoutev4Oper_method_names[2], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SLRoutev4VrfRegGet_(SLRoutev4Oper_method_names[3], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SLRoutev4VrfGetStats_(SLRoutev4Oper_method_names[4], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SLRoutev4Op_(SLRoutev4Oper_method_names[5], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SLRoutev4Get_(SLRoutev4Oper_method_names[6], ::grpc::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SLRoutev4OpStream_(SLRoutev4Oper_method_names[7], ::grpc::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_SLRoutev4GetStream_(SLRoutev4Oper_method_names[8], ::grpc::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status SLRoutev4Oper::Stub::SLRoutev4GlobalsGet(::grpc::ClientContext* context, const ::service_layer::SLRouteGlobalsGetMsg& request, ::service_layer::SLRouteGlobalsGetMsgRsp* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_SLRoutev4GlobalsGet_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::service_layer::SLRouteGlobalsGetMsgRsp>* SLRoutev4Oper::Stub::AsyncSLRoutev4GlobalsGetRaw(::grpc::ClientContext* context, const ::service_layer::SLRouteGlobalsGetMsg& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::service_layer::SLRouteGlobalsGetMsgRsp>(channel_.get(), cq, rpcmethod_SLRoutev4GlobalsGet_, context, request);
}

::grpc::Status SLRoutev4Oper::Stub::SLRoutev4GlobalStatsGet(::grpc::ClientContext* context, const ::service_layer::SLRouteGlobalStatsGetMsg& request, ::service_layer::SLRouteGlobalStatsGetMsgRsp* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_SLRoutev4GlobalStatsGet_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::service_layer::SLRouteGlobalStatsGetMsgRsp>* SLRoutev4Oper::Stub::AsyncSLRoutev4GlobalStatsGetRaw(::grpc::ClientContext* context, const ::service_layer::SLRouteGlobalStatsGetMsg& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::service_layer::SLRouteGlobalStatsGetMsgRsp>(channel_.get(), cq, rpcmethod_SLRoutev4GlobalStatsGet_, context, request);
}

::grpc::Status SLRoutev4Oper::Stub::SLRoutev4VrfRegOp(::grpc::ClientContext* context, const ::service_layer::SLVrfRegMsg& request, ::service_layer::SLVrfRegMsgRsp* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_SLRoutev4VrfRegOp_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::service_layer::SLVrfRegMsgRsp>* SLRoutev4Oper::Stub::AsyncSLRoutev4VrfRegOpRaw(::grpc::ClientContext* context, const ::service_layer::SLVrfRegMsg& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::service_layer::SLVrfRegMsgRsp>(channel_.get(), cq, rpcmethod_SLRoutev4VrfRegOp_, context, request);
}

::grpc::Status SLRoutev4Oper::Stub::SLRoutev4VrfRegGet(::grpc::ClientContext* context, const ::service_layer::SLVrfRegGetMsg& request, ::service_layer::SLVrfRegGetMsgRsp* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_SLRoutev4VrfRegGet_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::service_layer::SLVrfRegGetMsgRsp>* SLRoutev4Oper::Stub::AsyncSLRoutev4VrfRegGetRaw(::grpc::ClientContext* context, const ::service_layer::SLVrfRegGetMsg& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::service_layer::SLVrfRegGetMsgRsp>(channel_.get(), cq, rpcmethod_SLRoutev4VrfRegGet_, context, request);
}

::grpc::Status SLRoutev4Oper::Stub::SLRoutev4VrfGetStats(::grpc::ClientContext* context, const ::service_layer::SLVrfRegGetMsg& request, ::service_layer::SLVRFGetStatsMsgRsp* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_SLRoutev4VrfGetStats_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::service_layer::SLVRFGetStatsMsgRsp>* SLRoutev4Oper::Stub::AsyncSLRoutev4VrfGetStatsRaw(::grpc::ClientContext* context, const ::service_layer::SLVrfRegGetMsg& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::service_layer::SLVRFGetStatsMsgRsp>(channel_.get(), cq, rpcmethod_SLRoutev4VrfGetStats_, context, request);
}

::grpc::Status SLRoutev4Oper::Stub::SLRoutev4Op(::grpc::ClientContext* context, const ::service_layer::SLRoutev4Msg& request, ::service_layer::SLRoutev4MsgRsp* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_SLRoutev4Op_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::service_layer::SLRoutev4MsgRsp>* SLRoutev4Oper::Stub::AsyncSLRoutev4OpRaw(::grpc::ClientContext* context, const ::service_layer::SLRoutev4Msg& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::service_layer::SLRoutev4MsgRsp>(channel_.get(), cq, rpcmethod_SLRoutev4Op_, context, request);
}

::grpc::Status SLRoutev4Oper::Stub::SLRoutev4Get(::grpc::ClientContext* context, const ::service_layer::SLRoutev4GetMsg& request, ::service_layer::SLRoutev4GetMsgRsp* response) {
  return ::grpc::BlockingUnaryCall(channel_.get(), rpcmethod_SLRoutev4Get_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::service_layer::SLRoutev4GetMsgRsp>* SLRoutev4Oper::Stub::AsyncSLRoutev4GetRaw(::grpc::ClientContext* context, const ::service_layer::SLRoutev4GetMsg& request, ::grpc::CompletionQueue* cq) {
  return new ::grpc::ClientAsyncResponseReader< ::service_layer::SLRoutev4GetMsgRsp>(channel_.get(), cq, rpcmethod_SLRoutev4Get_, context, request);
}

::grpc::ClientReaderWriter< ::service_layer::SLRoutev4Msg, ::service_layer::SLRoutev4MsgRsp>* SLRoutev4Oper::Stub::SLRoutev4OpStreamRaw(::grpc::ClientContext* context) {
  return new ::grpc::ClientReaderWriter< ::service_layer::SLRoutev4Msg, ::service_layer::SLRoutev4MsgRsp>(channel_.get(), rpcmethod_SLRoutev4OpStream_, context);
}

::grpc::ClientAsyncReaderWriter< ::service_layer::SLRoutev4Msg, ::service_layer::SLRoutev4MsgRsp>* SLRoutev4Oper::Stub::AsyncSLRoutev4OpStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return new ::grpc::ClientAsyncReaderWriter< ::service_layer::SLRoutev4Msg, ::service_layer::SLRoutev4MsgRsp>(channel_.get(), cq, rpcmethod_SLRoutev4OpStream_, context, tag);
}

::grpc::ClientReaderWriter< ::service_layer::SLRoutev4GetMsg, ::service_layer::SLRoutev4GetMsgRsp>* SLRoutev4Oper::Stub::SLRoutev4GetStreamRaw(::grpc::ClientContext* context) {
  return new ::grpc::ClientReaderWriter< ::service_layer::SLRoutev4GetMsg, ::service_layer::SLRoutev4GetMsgRsp>(channel_.get(), rpcmethod_SLRoutev4GetStream_, context);
}

::grpc::ClientAsyncReaderWriter< ::service_layer::SLRoutev4GetMsg, ::service_layer::SLRoutev4GetMsgRsp>* SLRoutev4Oper::Stub::AsyncSLRoutev4GetStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return new ::grpc::ClientAsyncReaderWriter< ::service_layer::SLRoutev4GetMsg, ::service_layer::SLRoutev4GetMsgRsp>(channel_.get(), cq, rpcmethod_SLRoutev4GetStream_, context, tag);
}

SLRoutev4Oper::Service::Service() {
  (void)SLRoutev4Oper_method_names;
  AddMethod(new ::grpc::RpcServiceMethod(
      SLRoutev4Oper_method_names[0],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< SLRoutev4Oper::Service, ::service_layer::SLRouteGlobalsGetMsg, ::service_layer::SLRouteGlobalsGetMsgRsp>(
          std::mem_fn(&SLRoutev4Oper::Service::SLRoutev4GlobalsGet), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      SLRoutev4Oper_method_names[1],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< SLRoutev4Oper::Service, ::service_layer::SLRouteGlobalStatsGetMsg, ::service_layer::SLRouteGlobalStatsGetMsgRsp>(
          std::mem_fn(&SLRoutev4Oper::Service::SLRoutev4GlobalStatsGet), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      SLRoutev4Oper_method_names[2],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< SLRoutev4Oper::Service, ::service_layer::SLVrfRegMsg, ::service_layer::SLVrfRegMsgRsp>(
          std::mem_fn(&SLRoutev4Oper::Service::SLRoutev4VrfRegOp), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      SLRoutev4Oper_method_names[3],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< SLRoutev4Oper::Service, ::service_layer::SLVrfRegGetMsg, ::service_layer::SLVrfRegGetMsgRsp>(
          std::mem_fn(&SLRoutev4Oper::Service::SLRoutev4VrfRegGet), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      SLRoutev4Oper_method_names[4],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< SLRoutev4Oper::Service, ::service_layer::SLVrfRegGetMsg, ::service_layer::SLVRFGetStatsMsgRsp>(
          std::mem_fn(&SLRoutev4Oper::Service::SLRoutev4VrfGetStats), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      SLRoutev4Oper_method_names[5],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< SLRoutev4Oper::Service, ::service_layer::SLRoutev4Msg, ::service_layer::SLRoutev4MsgRsp>(
          std::mem_fn(&SLRoutev4Oper::Service::SLRoutev4Op), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      SLRoutev4Oper_method_names[6],
      ::grpc::RpcMethod::NORMAL_RPC,
      new ::grpc::RpcMethodHandler< SLRoutev4Oper::Service, ::service_layer::SLRoutev4GetMsg, ::service_layer::SLRoutev4GetMsgRsp>(
          std::mem_fn(&SLRoutev4Oper::Service::SLRoutev4Get), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      SLRoutev4Oper_method_names[7],
      ::grpc::RpcMethod::BIDI_STREAMING,
      new ::grpc::BidiStreamingHandler< SLRoutev4Oper::Service, ::service_layer::SLRoutev4Msg, ::service_layer::SLRoutev4MsgRsp>(
          std::mem_fn(&SLRoutev4Oper::Service::SLRoutev4OpStream), this)));
  AddMethod(new ::grpc::RpcServiceMethod(
      SLRoutev4Oper_method_names[8],
      ::grpc::RpcMethod::BIDI_STREAMING,
      new ::grpc::BidiStreamingHandler< SLRoutev4Oper::Service, ::service_layer::SLRoutev4GetMsg, ::service_layer::SLRoutev4GetMsgRsp>(
          std::mem_fn(&SLRoutev4Oper::Service::SLRoutev4GetStream), this)));
}

SLRoutev4Oper::Service::~Service() {
}

::grpc::Status SLRoutev4Oper::Service::SLRoutev4GlobalsGet(::grpc::ServerContext* context, const ::service_layer::SLRouteGlobalsGetMsg* request, ::service_layer::SLRouteGlobalsGetMsgRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SLRoutev4Oper::Service::SLRoutev4GlobalStatsGet(::grpc::ServerContext* context, const ::service_layer::SLRouteGlobalStatsGetMsg* request, ::service_layer::SLRouteGlobalStatsGetMsgRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SLRoutev4Oper::Service::SLRoutev4VrfRegOp(::grpc::ServerContext* context, const ::service_layer::SLVrfRegMsg* request, ::service_layer::SLVrfRegMsgRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SLRoutev4Oper::Service::SLRoutev4VrfRegGet(::grpc::ServerContext* context, const ::service_layer::SLVrfRegGetMsg* request, ::service_layer::SLVrfRegGetMsgRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SLRoutev4Oper::Service::SLRoutev4VrfGetStats(::grpc::ServerContext* context, const ::service_layer::SLVrfRegGetMsg* request, ::service_layer::SLVRFGetStatsMsgRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SLRoutev4Oper::Service::SLRoutev4Op(::grpc::ServerContext* context, const ::service_layer::SLRoutev4Msg* request, ::service_layer::SLRoutev4MsgRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SLRoutev4Oper::Service::SLRoutev4Get(::grpc::ServerContext* context, const ::service_layer::SLRoutev4GetMsg* request, ::service_layer::SLRoutev4GetMsgRsp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SLRoutev4Oper::Service::SLRoutev4OpStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service_layer::SLRoutev4MsgRsp, ::service_layer::SLRoutev4Msg>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status SLRoutev4Oper::Service::SLRoutev4GetStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::service_layer::SLRoutev4GetMsgRsp, ::service_layer::SLRoutev4GetMsg>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace service_layer

