// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: sl_version.proto
#ifndef GRPC_sl_5fversion_2eproto__INCLUDED
#define GRPC_sl_5fversion_2eproto__INCLUDED

#include "sl_version.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace service_layer {

}  // namespace service_layer


#endif  // GRPC_sl_5fversion_2eproto__INCLUDED
