#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#  @generated
#

from __future__ import absolute_import
import six
from thrift.util.Recursive import fix_spec
from thrift.Thrift import *
from thrift.protocol.TProtocol import TProtocolException


import openr.Fib.ttypes
import openr.Lsdb.ttypes


import pprint
import warnings
from thrift import Thrift
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
from thrift.protocol import TCompactProtocol
from thrift.protocol import THeaderProtocol
try:
  from thrift.protocol import fastproto
except:
  fastproto = None
all_structs = []
UTF8STRINGS = bool(0) or sys.version_info.major >= 3

__all__ = ['UTF8STRINGS', 'DecisionCommand', 'DecisionRequest', 'DecisionReply']

class DecisionCommand:
  ROUTE_DB_GET = 1
  ADJ_DB_GET = 2
  PREFIX_DB_GET = 3

  _VALUES_TO_NAMES = {
    1: "ROUTE_DB_GET",
    2: "ADJ_DB_GET",
    3: "PREFIX_DB_GET",
  }

  _NAMES_TO_VALUES = {
    "ROUTE_DB_GET": 1,
    "ADJ_DB_GET": 2,
    "PREFIX_DB_GET": 3,
  }

class DecisionRequest:
  """
  Attributes:
   - cmd
   - nodeName
  """

  thrift_spec = None
  thrift_field_annotations = None
  thrift_struct_annotations = None
  __init__ = None
  @staticmethod
  def isUnion():
    return False

  def read(self, iprot):
    if (isinstance(iprot, TBinaryProtocol.TBinaryProtocolAccelerated) or (isinstance(iprot, THeaderProtocol.THeaderProtocolAccelerate) and iprot.get_protocol_id() == THeaderProtocol.THeaderProtocol.T_BINARY_PROTOCOL)) and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastproto is not None:
      fastproto.decode(self, iprot.trans, [self.__class__, self.thrift_spec, False], utf8strings=UTF8STRINGS, protoid=0)
      self.checkRequired()
      return
    if (isinstance(iprot, TCompactProtocol.TCompactProtocolAccelerated) or (isinstance(iprot, THeaderProtocol.THeaderProtocolAccelerate) and iprot.get_protocol_id() == THeaderProtocol.THeaderProtocol.T_COMPACT_PROTOCOL)) and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastproto is not None:
      fastproto.decode(self, iprot.trans, [self.__class__, self.thrift_spec, False], utf8strings=UTF8STRINGS, protoid=2)
      self.checkRequired()
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.cmd = iprot.readI32()
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.nodeName = iprot.readString().decode('utf-8') if UTF8STRINGS else iprot.readString()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()
    self.checkRequired()

  def checkRequired(self):
    return

  def write(self, oprot):
    if (isinstance(oprot, TBinaryProtocol.TBinaryProtocolAccelerated) or (isinstance(oprot, THeaderProtocol.THeaderProtocolAccelerate) and oprot.get_protocol_id() == THeaderProtocol.THeaderProtocol.T_BINARY_PROTOCOL)) and self.thrift_spec is not None and fastproto is not None:
      oprot.trans.write(fastproto.encode(self, [self.__class__, self.thrift_spec, False], utf8strings=UTF8STRINGS, protoid=0))
      return
    if (isinstance(oprot, TCompactProtocol.TCompactProtocolAccelerated) or (isinstance(oprot, THeaderProtocol.THeaderProtocolAccelerate) and oprot.get_protocol_id() == THeaderProtocol.THeaderProtocol.T_COMPACT_PROTOCOL)) and self.thrift_spec is not None and fastproto is not None:
      oprot.trans.write(fastproto.encode(self, [self.__class__, self.thrift_spec, False], utf8strings=UTF8STRINGS, protoid=2))
      return
    oprot.writeStructBegin('DecisionRequest')
    if self.cmd != None:
      oprot.writeFieldBegin('cmd', TType.I32, 1)
      oprot.writeI32(self.cmd)
      oprot.writeFieldEnd()
    if self.nodeName != None:
      oprot.writeFieldBegin('nodeName', TType.STRING, 2)
      oprot.writeString(self.nodeName.encode('utf-8')) if UTF8STRINGS and not isinstance(self.nodeName, bytes) else oprot.writeString(self.nodeName)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def __repr__(self):
    L = []
    padding = ' ' * 4
    value = pprint.pformat(self.cmd, indent=0)
    value = padding.join(value.splitlines(True))
    L.append('    cmd=%s' % (value))
    value = pprint.pformat(self.nodeName, indent=0)
    value = padding.join(value.splitlines(True))
    L.append('    nodeName=%s' % (value))
    return "%s(\n%s)" % (self.__class__.__name__, ",\n".join(L))

  def __eq__(self, other):
    if not isinstance(other, self.__class__):
      return False

    return self.__dict__ == other.__dict__ 

  def __ne__(self, other):
    return not (self == other)

  # Override the __hash__ function for Python3 - t10434117
  if not six.PY2:
    __hash__ = object.__hash__

class DecisionReply:
  """
  Attributes:
   - routeDb
   - adjDbs
   - prefixDbs
  """

  thrift_spec = None
  thrift_field_annotations = None
  thrift_struct_annotations = None
  __init__ = None
  @staticmethod
  def isUnion():
    return False

  def read(self, iprot):
    if (isinstance(iprot, TBinaryProtocol.TBinaryProtocolAccelerated) or (isinstance(iprot, THeaderProtocol.THeaderProtocolAccelerate) and iprot.get_protocol_id() == THeaderProtocol.THeaderProtocol.T_BINARY_PROTOCOL)) and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastproto is not None:
      fastproto.decode(self, iprot.trans, [self.__class__, self.thrift_spec, False], utf8strings=UTF8STRINGS, protoid=0)
      self.checkRequired()
      return
    if (isinstance(iprot, TCompactProtocol.TCompactProtocolAccelerated) or (isinstance(iprot, THeaderProtocol.THeaderProtocolAccelerate) and iprot.get_protocol_id() == THeaderProtocol.THeaderProtocol.T_COMPACT_PROTOCOL)) and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastproto is not None:
      fastproto.decode(self, iprot.trans, [self.__class__, self.thrift_spec, False], utf8strings=UTF8STRINGS, protoid=2)
      self.checkRequired()
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRUCT:
          self.routeDb = openr.Fib.ttypes.RouteDatabase()
          self.routeDb.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.MAP:
          self.adjDbs = {}
          (_ktype1, _vtype2, _size0 ) = iprot.readMapBegin() 
          if _size0 >= 0:
            for _i4 in six.moves.range(_size0):
              _key5 = iprot.readString().decode('utf-8') if UTF8STRINGS else iprot.readString()
              _val6 = openr.Lsdb.ttypes.AdjacencyDatabase()
              _val6.read(iprot)
              self.adjDbs[_key5] = _val6
          else: 
            while iprot.peekMap():
              _key7 = iprot.readString().decode('utf-8') if UTF8STRINGS else iprot.readString()
              _val8 = openr.Lsdb.ttypes.AdjacencyDatabase()
              _val8.read(iprot)
              self.adjDbs[_key7] = _val8
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.MAP:
          self.prefixDbs = {}
          (_ktype10, _vtype11, _size9 ) = iprot.readMapBegin() 
          if _size9 >= 0:
            for _i13 in six.moves.range(_size9):
              _key14 = iprot.readString().decode('utf-8') if UTF8STRINGS else iprot.readString()
              _val15 = openr.Lsdb.ttypes.PrefixDatabase()
              _val15.read(iprot)
              self.prefixDbs[_key14] = _val15
          else: 
            while iprot.peekMap():
              _key16 = iprot.readString().decode('utf-8') if UTF8STRINGS else iprot.readString()
              _val17 = openr.Lsdb.ttypes.PrefixDatabase()
              _val17.read(iprot)
              self.prefixDbs[_key16] = _val17
          iprot.readMapEnd()
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()
    self.checkRequired()

  def checkRequired(self):
    return

  def write(self, oprot):
    if (isinstance(oprot, TBinaryProtocol.TBinaryProtocolAccelerated) or (isinstance(oprot, THeaderProtocol.THeaderProtocolAccelerate) and oprot.get_protocol_id() == THeaderProtocol.THeaderProtocol.T_BINARY_PROTOCOL)) and self.thrift_spec is not None and fastproto is not None:
      oprot.trans.write(fastproto.encode(self, [self.__class__, self.thrift_spec, False], utf8strings=UTF8STRINGS, protoid=0))
      return
    if (isinstance(oprot, TCompactProtocol.TCompactProtocolAccelerated) or (isinstance(oprot, THeaderProtocol.THeaderProtocolAccelerate) and oprot.get_protocol_id() == THeaderProtocol.THeaderProtocol.T_COMPACT_PROTOCOL)) and self.thrift_spec is not None and fastproto is not None:
      oprot.trans.write(fastproto.encode(self, [self.__class__, self.thrift_spec, False], utf8strings=UTF8STRINGS, protoid=2))
      return
    oprot.writeStructBegin('DecisionReply')
    if self.routeDb != None:
      oprot.writeFieldBegin('routeDb', TType.STRUCT, 1)
      self.routeDb.write(oprot)
      oprot.writeFieldEnd()
    if self.adjDbs != None:
      oprot.writeFieldBegin('adjDbs', TType.MAP, 2)
      oprot.writeMapBegin(TType.STRING, TType.STRUCT, len(self.adjDbs))
      for kiter18,viter19 in self.adjDbs.items():
        oprot.writeString(kiter18.encode('utf-8')) if UTF8STRINGS and not isinstance(kiter18, bytes) else oprot.writeString(kiter18)
        viter19.write(oprot)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    if self.prefixDbs != None:
      oprot.writeFieldBegin('prefixDbs', TType.MAP, 3)
      oprot.writeMapBegin(TType.STRING, TType.STRUCT, len(self.prefixDbs))
      for kiter20,viter21 in self.prefixDbs.items():
        oprot.writeString(kiter20.encode('utf-8')) if UTF8STRINGS and not isinstance(kiter20, bytes) else oprot.writeString(kiter20)
        viter21.write(oprot)
      oprot.writeMapEnd()
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def __repr__(self):
    L = []
    padding = ' ' * 4
    value = pprint.pformat(self.routeDb, indent=0)
    value = padding.join(value.splitlines(True))
    L.append('    routeDb=%s' % (value))
    value = pprint.pformat(self.adjDbs, indent=0)
    value = padding.join(value.splitlines(True))
    L.append('    adjDbs=%s' % (value))
    value = pprint.pformat(self.prefixDbs, indent=0)
    value = padding.join(value.splitlines(True))
    L.append('    prefixDbs=%s' % (value))
    return "%s(\n%s)" % (self.__class__.__name__, ",\n".join(L))

  def __eq__(self, other):
    if not isinstance(other, self.__class__):
      return False

    return self.__dict__ == other.__dict__ 

  def __ne__(self, other):
    return not (self == other)

  # Override the __hash__ function for Python3 - t10434117
  if not six.PY2:
    __hash__ = object.__hash__

all_structs.append(DecisionRequest)
DecisionRequest.thrift_spec = (
  None, # 0
  (1, TType.I32, 'cmd', DecisionCommand, None, 2, ), # 1
  (2, TType.STRING, 'nodeName', True, None, 2, ), # 2
)

DecisionRequest.thrift_struct_annotations = {
}
DecisionRequest.thrift_field_annotations = {
}

def DecisionRequest__init__(self, cmd=None, nodeName=None,):
  self.cmd = cmd
  self.nodeName = nodeName

DecisionRequest.__init__ = DecisionRequest__init__

all_structs.append(DecisionReply)
DecisionReply.thrift_spec = (
  None, # 0
  (1, TType.STRUCT, 'routeDb', [openr.Fib.ttypes.RouteDatabase, openr.Fib.ttypes.RouteDatabase.thrift_spec, False], None, 2, ), # 1
  (2, TType.MAP, 'adjDbs', (TType.STRING,True,TType.STRUCT,[openr.Lsdb.ttypes.AdjacencyDatabase, openr.Lsdb.ttypes.AdjacencyDatabase.thrift_spec, False]), None, 2, ), # 2
  (3, TType.MAP, 'prefixDbs', (TType.STRING,True,TType.STRUCT,[openr.Lsdb.ttypes.PrefixDatabase, openr.Lsdb.ttypes.PrefixDatabase.thrift_spec, False]), None, 2, ), # 3
)

DecisionReply.thrift_struct_annotations = {
}
DecisionReply.thrift_field_annotations = {
}

def DecisionReply__init__(self, routeDb=None, adjDbs=None, prefixDbs=None,):
  self.routeDb = routeDb
  self.adjDbs = adjDbs
  self.prefixDbs = prefixDbs

DecisionReply.__init__ = DecisionReply__init__

fix_spec(all_structs)
del all_structs
