/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

/*
 * ScaleTestServer - Real network scale testing against a DUT
 *
 * This binary connects to a real OpenR switch (FBOSS/EOS) via VLAN trunk
 * and runs scale tests using SparkFaker (for neighbor simulation) and
 * KvStoreThriftInjector (for topology injection).
 *
 * Usage:
 *   buck2 run fbcode//openr/tests/scale:scale_test_server -- \
 *     --dut_host=192.168.1.1 \
 *     --interfaces=eth0.1,eth0.2,eth0.3,eth0.4 \
 *     --num_spines=64 \
 *     --num_leaves=252
 */

#include <arpa/inet.h>
#include <ifaddrs.h>
#include <net/if.h>
#include <netinet/in.h>
#include <chrono>
#include <csignal>
#include <thread>

#include <fmt/format.h>
#include <folly/init/Init.h>
#include <gflags/gflags.h>
#include <glog/logging.h>

#include <openr/tests/scale/DutMonitor.h>
#include <openr/tests/scale/FakeKvStoreManager.h>
#include <openr/tests/scale/KvStoreThriftInjector.h>
#include <openr/tests/scale/RealSparkIo.h>
#include <openr/tests/scale/SparkFaker.h>
#include <openr/tests/scale/TopologyGenerator.h>

DEFINE_string(dut_host, "192.168.1.1", "DUT hostname or IP address");

DEFINE_int32(dut_port, 2018, "DUT OpenR thrift port");

DEFINE_string(
    interfaces,
    "",
    "Comma-separated list of VLAN interfaces (e.g., eth0.1,eth0.2,eth0.3,eth0.4)");

DEFINE_int32(num_spines, 64, "Number of spine neighbors to simulate");

DEFINE_int32(num_leaves, 252, "Number of leaf nodes in the topology");

DEFINE_int32(
    num_super_spines,
    0,
    "Number of super-spine nodes (0 for 2-tier, >0 for 3-tier)");

DEFINE_int32(num_pods, 8, "Number of pods in the topology");

DEFINE_int32(
    num_prefixes_per_node, 11, "Number of prefixes each router advertises");

DEFINE_string(
    topology_type,
    "bbf-simple",
    "Topology type: bbf-simple, bbf-full, or custom");

DEFINE_bool(
    inject_topology, true, "Inject the full topology into DUT's KvStore");

DEFINE_bool(
    simulate_neighbors, true, "Simulate Spark neighbors via real UDP packets");

DEFINE_int32(
    run_duration_sec,
    0,
    "Duration to run in seconds (0 = run until interrupted)");

DEFINE_bool(verify_routes, true, "Verify routes are computed after injection");

DEFINE_int32(
    fake_kvstore_base_port,
    3000,
    "Base port for per-neighbor FakeKvStore Thrift servers");

DEFINE_bool(
    enable_fake_kvstore,
    true,
    "Enable per-neighbor FakeKvStore servers for KvStore sync");

DEFINE_int32(
    num_fake_keys_per_node,
    0,
    "Number of fake keys per node (0 = disabled). "
    "Simulates extra key injection like fakekeys0:<nodeName>, fakekeys1:<nodeName>, ...");

DEFINE_int32(
    fake_key_version_bump_interval_sec,
    60,
    "Interval in seconds to bump fake key versions (0 = disabled). "
    "Simulates LSP agent periodically updating keys.");

namespace {

/*
 * Node ID for the DUT router entry in the topology. Chosen to be well
 * above any simulated router ID so it never collides.
 */
constexpr int kDutNodeId{99999};

std::atomic<bool> g_running{true};

void
signalHandler(int /* signal */) {
  LOG(INFO) << "Received interrupt signal, shutting down...";
  g_running.store(false);
}

/*
 * Parse comma-separated interface list into vector
 */
std::vector<std::string>
parseInterfaces(const std::string& interfaces) {
  std::vector<std::string> result;
  std::stringstream ss(interfaces);
  std::string item;
  while (std::getline(ss, item, ',')) {
    if (!item.empty()) {
      result.push_back(item);
    }
  }
  return result;
}

/*
 * Get interface index from name using if_nametoindex
 */
int
getIfIndex(const std::string& ifName) {
  unsigned int idx = if_nametoindex(ifName.c_str());
  if (idx == 0) {
    LOG(ERROR) << "Failed to get ifIndex for " << ifName << ": "
               << strerror(errno);
    return -1;
  }
  return static_cast<int>(idx);
}

/*
 * Check if an IPv6 link-local address is auto-generated via EUI-64.
 * EUI-64 addresses have 0xff 0xfe at bytes 11-12 of the address,
 * derived from the interface MAC address. Configured addresses
 * (manually assigned) won't have this pattern.
 */
bool
isEui64LinkLocal(const struct in6_addr& addr) {
  return addr.s6_addr[11] == 0xff && addr.s6_addr[12] == 0xfe;
}

/*
 * Get all link-local IPv6 addresses of an interface using getifaddrs().
 * Returns all fe80:: addresses found, ordered so that configured (non-EUI-64)
 * addresses come before auto-generated (EUI-64) ones. This way the caller
 * can prefer the configured address by picking the first element.
 */
std::vector<std::string>
getIfLinkLocalAddrs(const std::string& ifName) {
  struct ifaddrs* ifaddr = nullptr;
  if (getifaddrs(&ifaddr) == -1) {
    LOG(ERROR) << "getifaddrs failed: " << strerror(errno);
    return {};
  }

  std::vector<std::string> configured;
  std::vector<std::string> autoGenerated;
  for (auto* ifa = ifaddr; ifa != nullptr; ifa = ifa->ifa_next) {
    if (ifa->ifa_addr == nullptr || ifa->ifa_addr->sa_family != AF_INET6) {
      continue;
    }
    if (ifName != ifa->ifa_name) {
      continue;
    }
    auto* sin6 = reinterpret_cast<struct sockaddr_in6*>(ifa->ifa_addr);
    if (!IN6_IS_ADDR_LINKLOCAL(&sin6->sin6_addr)) {
      continue;
    }
    char buf[INET6_ADDRSTRLEN];
    if (inet_ntop(AF_INET6, &sin6->sin6_addr, buf, sizeof(buf))) {
      if (isEui64LinkLocal(sin6->sin6_addr)) {
        autoGenerated.emplace_back(buf);
      } else {
        configured.emplace_back(buf);
      }
    }
  }

  freeifaddrs(ifaddr);

  /*
   * Return configured addresses first so the caller prefers them.
   */
  std::vector<std::string> result;
  result.reserve(configured.size() + autoGenerated.size());
  result.insert(result.end(), configured.begin(), configured.end());
  result.insert(result.end(), autoGenerated.begin(), autoGenerated.end());

  if (result.empty()) {
    LOG(WARNING) << "No link-local IPv6 address found on " << ifName;
  }
  return result;
}

} // namespace

int
main(int argc, char** argv) {
  folly::Init init(&argc, &argv);
  google::SetStderrLogging(google::INFO);

  std::signal(SIGINT, signalHandler);
  std::signal(SIGTERM, signalHandler);

  LOG(INFO) << "\n"
            << "╔══════════════════════════════════════════════════════════╗\n"
            << "║          OpenR Scale Test Server                         ║\n"
            << "╚══════════════════════════════════════════════════════════╝";

  LOG(INFO) << fmt::format("[SCALE-TEST] Configuration:");
  LOG(INFO) << fmt::format(
      "  DUT Host:        {}:{}", FLAGS_dut_host, FLAGS_dut_port);
  LOG(INFO) << fmt::format("  Topology:        {}", FLAGS_topology_type);
  LOG(INFO) << fmt::format("  Spines:          {}", FLAGS_num_spines);
  LOG(INFO) << fmt::format("  Leaves:          {}", FLAGS_num_leaves);
  LOG(INFO) << fmt::format("  Super-spines:    {}", FLAGS_num_super_spines);
  LOG(INFO) << fmt::format("  Pods:            {}", FLAGS_num_pods);
  LOG(INFO)
      << fmt::format("  Prefixes/node:   {}", FLAGS_num_prefixes_per_node);
  LOG(INFO) << fmt::format(
      "  Interfaces:      {}",
      FLAGS_interfaces.empty() ? "(none)" : FLAGS_interfaces);
  LOG(INFO) << fmt::format(
      "  Inject topology: {}", FLAGS_inject_topology ? "yes" : "no");
  LOG(INFO) << fmt::format(
      "  Simulate nbrs:   {}", FLAGS_simulate_neighbors ? "yes" : "no");
  LOG(INFO) << fmt::format(
      "  Verify routes:   {}", FLAGS_verify_routes ? "yes" : "no");
  LOG(INFO) << fmt::format(
      "  FakeKvStore:     {}",
      FLAGS_enable_fake_kvstore
          ? fmt::format("yes (base port {})", FLAGS_fake_kvstore_base_port)
          : "no");
  LOG(INFO)
      << fmt::format("  Fake keys/node:  {}", FLAGS_num_fake_keys_per_node);
  LOG(INFO) << fmt::format(
      "  Fake key bump:   {} sec (0=disabled)",
      FLAGS_fake_key_version_bump_interval_sec);
  LOG(INFO) << fmt::format(
      "  Run duration:    {} sec (0=infinite)", FLAGS_run_duration_sec);
  LOG(INFO) << "";
  LOG(INFO)
      << "TIP: Use -v=1 for detailed state transitions, -v=2 for packet-level debug";
  LOG(INFO) << "";

  /*
   * Parse interfaces
   */
  auto interfaces = parseInterfaces(FLAGS_interfaces);
  if (interfaces.empty() && FLAGS_simulate_neighbors) {
    LOG(ERROR) << "No interfaces specified. Use --interfaces=eth0.1,eth0.2,...";
    return 1;
  }

  LOG(INFO) << fmt::format("Interfaces: {}", FLAGS_interfaces);

  /*
   * Generate topology
   */
  LOG(INFO) << "Generating topology...";
  openr::Topology topology;

  if (FLAGS_topology_type == "bbf-simple") {
    topology = openr::TopologyGenerator::createBbfSimple(
        FLAGS_num_spines,
        FLAGS_num_leaves,
        FLAGS_num_super_spines,
        FLAGS_num_pods,
        FLAGS_num_prefixes_per_node);
  } else if (FLAGS_topology_type == "bbf-full") {
    topology = openr::TopologyGenerator::createBbf(
        FLAGS_num_spines,
        FLAGS_num_leaves,
        FLAGS_num_super_spines,
        FLAGS_num_pods,
        openr::kDefaultBbfEcmpWidth,
        FLAGS_num_prefixes_per_node);
  } else {
    LOG(ERROR) << "Unknown topology type: " << FLAGS_topology_type;
    return 1;
  }

  LOG(INFO) << fmt::format(
      "Generated topology: {} routers, {} adjacencies, {} prefixes",
      topology.getRouterCount(),
      topology.getTotalAdjacencyCount(),
      topology.getTotalPrefixCount());

  /*
   * Connect to DUT
   */
  openr::KvStoreThriftInjector injector(FLAGS_dut_host, FLAGS_dut_port);
  openr::DutMonitor monitor(FLAGS_dut_host, FLAGS_dut_port);

  if (!injector.connect()) {
    LOG(ERROR) << "Failed to connect to DUT";
    return 1;
  }

  if (!monitor.connect()) {
    LOG(ERROR) << "Failed to connect DutMonitor to DUT";
    return 1;
  }

  auto dutNodeName = injector.getDutNodeName();
  LOG(INFO) << "Connected to DUT: " << dutNodeName;

  /*
   * Add DUT as a router in the topology so that spine adj DBs
   * include the DUT as a neighbor. Decision requires bidirectional
   * adjacency — both sides must report the link. The DUT's own
   * adj DB is created by its LinkMonitor via SparkFaker, but the
   * injected spine adj DBs must also list the DUT.
   */
  if (FLAGS_simulate_neighbors && !interfaces.empty()) {
    openr::VirtualRouter dutRouter;
    dutRouter.nodeName = dutNodeName;
    dutRouter.nodeId = kDutNodeId;
    dutRouter.nodeLabel = 0;
    topology.routers.emplace(dutNodeName, std::move(dutRouter));

    int neighborsPerInterface =
        static_cast<int>(FLAGS_num_spines / interfaces.size());
    int neighborIdx = 0;

    for (size_t i = 0; i < interfaces.size(); ++i) {
      const auto& ifName = interfaces[i];
      int neighborsOnThisIf = (i == interfaces.size() - 1)
          ? (FLAGS_num_spines - neighborIdx)
          : neighborsPerInterface;

      for (int j = 0; j < neighborsOnThisIf && neighborIdx < FLAGS_num_spines;
           ++j, ++neighborIdx) {
        std::string spineName = fmt::format("spine-{}", neighborIdx);
        std::string spineIfName = fmt::format("{}-to-dut", spineName);

        auto& spineRouter = topology.routers.at(spineName);

        openr::VirtualAdjacency dutAdj;
        dutAdj.localIfName = spineIfName;
        dutAdj.remoteRouterName = dutNodeName;
        dutAdj.remoteIfName = ifName;
        dutAdj.metric = 1;
        dutAdj.latencyMs = 1;
        spineRouter.adjacencies.push_back(std::move(dutAdj));
      }
    }

    LOG(INFO) << fmt::format(
        "Added DUT '{}' to topology with {} spine->DUT adjacencies",
        dutNodeName,
        FLAGS_num_spines);
  }

  /*
   * Setup FakeKvStoreManager (per-neighbor KvStore Thrift servers)
   */
  std::unique_ptr<openr::FakeKvStoreManager> kvManager;
  std::vector<std::string> neighborNames;

  if (FLAGS_enable_fake_kvstore && FLAGS_simulate_neighbors) {
    LOG(INFO) << "Setting up FakeKvStoreManager...";

    kvManager = std::make_unique<openr::FakeKvStoreManager>(
        FLAGS_fake_kvstore_base_port, 4);

    /*
     * Collect neighbor names
     */
    for (int i = 0; i < FLAGS_num_spines; ++i) {
      neighborNames.push_back(fmt::format("spine-{}", i));
    }

    /*
     * Build shared KV data from topology
     */
    LOG(INFO) << fmt::format(
        "Building KV data for {} neighbors...", neighborNames.size());
    auto allKeyVals = openr::KvStoreThriftInjector::buildKeyVals(
        topology, FLAGS_num_fake_keys_per_node);

    /*
     * Remove the DUT's own adj key — LinkMonitor handles that.
     * We only want spine/leaf adj DBs in the shared data.
     */
    allKeyVals.erase(fmt::format("adj:{}", dutNodeName));

    auto sharedKeyVals =
        std::make_shared<const openr::thrift::KeyVals>(std::move(allKeyVals));
    LOG(INFO) << fmt::format("Built {} shared keys", sharedKeyVals->size());

    /*
     * Add each neighbor to the manager
     */
    for (const auto& name : neighborNames) {
      kvManager->addNeighbor(name, sharedKeyVals);
    }

    LOG(INFO) << fmt::format(
        "FakeKvStoreManager configured with {} neighbors (ports {}-{})",
        kvManager->getNeighborCount(),
        FLAGS_fake_kvstore_base_port,
        FLAGS_fake_kvstore_base_port + kvManager->getNeighborCount() - 1);
  }

  /*
   * Setup SparkFaker with real I/O (if simulating neighbors)
   */
  std::shared_ptr<openr::SparkFaker> faker;
  std::shared_ptr<openr::RealSparkIo> realIo;

  if (FLAGS_simulate_neighbors && !interfaces.empty()) {
    LOG(INFO) << "Setting up SparkFaker with real network I/O...";

    realIo = std::make_shared<openr::RealSparkIo>();

    /*
     * Distribute spines across interfaces
     */
    int neighborsPerInterface = FLAGS_num_spines / interfaces.size();
    int neighborIdx = 0;

    faker = std::make_shared<openr::SparkFaker>(realIo);

    for (size_t i = 0; i < interfaces.size(); ++i) {
      const auto& ifName = interfaces[i];
      int ifIndex = getIfIndex(ifName);

      if (ifIndex < 0) {
        LOG(WARNING) << "Skipping interface " << ifName << " (not found)";
        continue;
      }

      /*
       * Get all link-local addresses of this interface.
       * An interface may have both a configured and an auto-generated
       * (EUI-64) link-local address. Configured addresses are returned
       * first so we prefer them.
       */
      auto ifLinkLocalAddrs = getIfLinkLocalAddrs(ifName);
      if (ifLinkLocalAddrs.empty()) {
        LOG(WARNING) << "Skipping interface " << ifName
                     << " (no link-local address)";
        continue;
      }
      const auto& ifLinkLocal = ifLinkLocalAddrs.front();
      if (ifLinkLocalAddrs.size() > 1) {
        LOG(INFO) << fmt::format(
            "Interface {} has {} link-local addresses, using {} (configured addresses preferred over auto-generated EUI-64)",
            ifName,
            ifLinkLocalAddrs.size(),
            ifLinkLocal);
        for (const auto& addr : ifLinkLocalAddrs) {
          LOG(INFO) << fmt::format("  - {}", addr);
        }
      }

      /*
       * Add neighbors for this interface
       */
      int neighborsOnThisIf = (i == interfaces.size() - 1)
          ? (FLAGS_num_spines - neighborIdx)
          : neighborsPerInterface;

      for (int j = 0; j < neighborsOnThisIf && neighborIdx < FLAGS_num_spines;
           ++j, ++neighborIdx) {
        std::string spineName = fmt::format("spine-{}", neighborIdx);
        std::string spineIfName = fmt::format("{}-to-dut", spineName);

        /*
         * Use the real link-local IPv6 address of the interface.
         * Each spine is differentiated by its unique thrift ctrl port.
         */
        std::string v6Addr = ifLinkLocal;

        /*
         * Generate IPv4 address matching setup_vlans.sh scheme:
         * test server = 10.0.<vlan>.1, DUT = 10.0.<vlan>.2
         * Extract VLAN ID from interface name (e.g., "et4_15_1.3" -> 3)
         */
        std::string v4Addr = "0.0.0.0";
        auto dotPos = ifName.rfind('.');
        if (dotPos != std::string::npos) {
          try {
            int vlanId = std::stoi(ifName.substr(dotPos + 1));
            int v4o2 = vlanId / 256;
            int v4o3 = vlanId % 256;
            v4Addr = fmt::format("10.{}.{}.1", v4o2, v4o3);
          } catch (const std::exception&) {
            /* not a numeric VLAN suffix, keep 0.0.0.0 */
          }
        }

        faker->addNeighbor(
            spineName, spineIfName, ifIndex, v6Addr, ifName, ifIndex, v4Addr);

        /*
         * Set the per-neighbor ctrl port for KvStore sync
         */
        if (kvManager) {
          uint16_t ctrlPort = kvManager->getPort(spineName);
          faker->setNeighborCtrlPort(spineName, ctrlPort);
          VLOG(2)
              << fmt::format("Set ctrlPort for {} to {}", spineName, ctrlPort);
        }

        VLOG(1) << fmt::format(
            "Added fake neighbor {} on {} ({})", spineName, ifName, v6Addr);
      }

      LOG(INFO) << fmt::format(
          "Interface {}: {} neighbors", ifName, neighborsOnThisIf);
    }

    LOG(INFO) << fmt::format(
        "SparkFaker configured with {} neighbors across {} interfaces",
        faker->getNeighborCount(),
        interfaces.size());
  }

  /*
   * Inject topology
   */
  if (FLAGS_inject_topology) {
    LOG(INFO) << "Injecting topology into DUT KvStore...";
    auto startTime = std::chrono::steady_clock::now();

    auto keyVals = openr::KvStoreThriftInjector::buildKeyVals(
        topology, FLAGS_num_fake_keys_per_node);

    /*
     * Remove the DUT's own adj key — LinkMonitor handles that.
     * Injecting it would conflict with LinkMonitor's version.
     */
    keyVals.erase(fmt::format("adj:{}", dutNodeName));

    size_t keysInjected = injector.injectKeyVals(keyVals);

    auto endTime = std::chrono::steady_clock::now();
    auto durationMs = std::chrono::duration_cast<std::chrono::milliseconds>(
                          endTime - startTime)
                          .count();

    LOG(INFO) << fmt::format(
        "Injected {} keys in {} ms ({} keys/sec)",
        keysInjected,
        durationMs,
        durationMs > 0 ? (keysInjected * 1000 / durationMs) : 0);
  }

  /*
   * Start FakeKvStoreManager (BEFORE SparkFaker so DUT can connect to us)
   */
  if (kvManager) {
    LOG(INFO) << "Starting FakeKvStoreManager...";
    kvManager->start();
  }

  /*
   * Start SparkFaker (if simulating neighbors)
   */
  if (faker) {
    LOG(INFO) << "Starting SparkFaker...";
    faker->start();
  }

  /*
   * Wait for route computation (if verifying)
   */
  if (FLAGS_verify_routes) {
    LOG(INFO) << "Waiting for route computation...";
    std::this_thread::sleep_for(std::chrono::seconds(5));

    auto routeDb = injector.getRouteDatabase(dutNodeName);
    LOG(INFO) << fmt::format(
        "DUT computed {} unicast routes, {} MPLS routes",
        routeDb.unicastRoutes()->size(),
        routeDb.mplsRoutes()->size());
  }

  /*
   * Main loop
   */
  LOG(INFO) << "=== Scale test running. Press Ctrl+C to stop. ===";

  auto startTime = std::chrono::steady_clock::now();
  int64_t lastStatsTime = 0;
  int64_t lastFakeKeyBumpTime = 0;
  int64_t fakeKeyVersion = 1;

  while (g_running.load()) {
    std::this_thread::sleep_for(std::chrono::seconds(1));

    auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(
                       std::chrono::steady_clock::now() - startTime)
                       .count();

    if (FLAGS_run_duration_sec > 0 && elapsed >= FLAGS_run_duration_sec) {
      LOG(INFO) << "[SCALE-TEST] Run duration reached, stopping...";
      break;
    }

    /*
     * Periodic fake key version bump (simulates LSP agent)
     */
    if (FLAGS_num_fake_keys_per_node > 0 &&
        FLAGS_fake_key_version_bump_interval_sec > 0 &&
        elapsed - lastFakeKeyBumpTime >=
            FLAGS_fake_key_version_bump_interval_sec) {
      lastFakeKeyBumpTime = elapsed;
      ++fakeKeyVersion;

      openr::thrift::KeyVals fakeKeyVals;
      for (const auto& [nodeName, router] : topology.routers) {
        auto fakeKvs = openr::KvStoreThriftInjector::createFakeKeyValues(
            router, FLAGS_num_fake_keys_per_node, fakeKeyVersion);
        for (auto& [key, value] : fakeKvs) {
          fakeKeyVals.emplace(std::move(key), std::move(value));
        }
      }

      if (injector.isConnected()) {
        injector.injectKeyVals(fakeKeyVals);
      }

      if (kvManager) {
        kvManager->propagateKeyUpdates(fakeKeyVals);
      }

      LOG(INFO) << fmt::format(
          "[SCALE-TEST] Bumped fake key versions to {} ({} keys)",
          fakeKeyVersion,
          fakeKeyVals.size());
    }

    /*
     * Periodic stats every 10 seconds
     */
    if (elapsed - lastStatsTime >= 10) {
      lastStatsTime = elapsed;

      LOG(INFO) << fmt::format(
          "\n========== Status at {} seconds ==========", elapsed);

      if (faker) {
        LOG(INFO) << faker->getStatsReport();
        VLOG(1) << faker->getNeighborStatusReport();
      }

      /*
       * Query DUT OpenR counters
       */
      if (monitor.isConnected()) {
        auto counters = monitor.getRegexCounters(
            "process\\.cpu\\.peak_pct|process\\.cpu\\.pct|"
            "process\\.memory\\.rss|"
            "kvstore\\.received_key_vals\\.sum|"
            "kvstore\\.updated_key_vals\\.sum|"
            "kvstore\\.thrift\\.num_flood_pub_success\\.count|"
            "kvstore\\.thrift\\.flood_pub_duration_ms\\.avg|"
            "kvstore\\.thrift\\.finalized_sync_duration_ms\\.avg|"
            "kvstore\\.thrift\\.full_sync_duration_ms\\.avg|"
            "decision\\.route_build_ms\\.avg|"
            "fib\\.route_programming\\.time_ms\\.avg|"
            "decision\\.spf_ms\\.avg|"
            "decision\\.path_build_ms\\.avg|"
            "fib\\.route_sync\\.time_ms|"
            "initialization\\.KVSTORE_SYNCED\\.duration_ms|"
            "initialization\\.INITIALIZED\\.duration_ms|"
            "decision\\.linkstate\\.up\\.propagation_time_ms|"
            "decision\\.linkstate\\.down\\.propagation_time_ms");
        if (!counters.empty()) {
          std::string report = "\n=== DUT OpenR Counters ===\n";
          for (const auto& [name, value] : counters) {
            report += fmt::format("  {}: {}\n", name, value);
          }
          LOG(INFO) << report;
        }
      }
    }
  }

  /*
   * Final stats
   */
  LOG(INFO) << "\n========== Final Statistics ==========";
  if (faker) {
    LOG(INFO) << faker->getStatsReport();
    LOG(INFO) << faker->getNeighborStatusReport();
  }

  /*
   * Cleanup
   */
  LOG(INFO) << "[SCALE-TEST] Shutting down...";

  if (faker) {
    faker->stop();
  }

  if (kvManager) {
    kvManager->stop();
  }

  monitor.disconnect();
  injector.disconnect();

  LOG(INFO) << "[SCALE-TEST] Scale test complete.";
  return 0;
}
